// Bakes the glyphs and emoji the card renderer needs into an atlas, using a headless
// browser at build time. The Worker then only has to blit pixels -- no font parsing, no
// WASM, no runtime font loading.
//
// The emoji set is closed: every emoji comes from src/content/, so we know all of them
// up front. Re-run this after adding an emoji to the content tables -- npm test fails if
// the atlas is missing one.
//
//   npm run atlas
//
// which installs Playwright without saving it, then runs this. Cloud sessions already have
// Chromium at $PLAYWRIGHT_BROWSERS_PATH, so nothing is downloaded.
//
// Playwright is deliberately not a dependency: the atlas is committed, so nothing but this
// script needs it, and CI shouldn't install a browser to deploy.

import { chromium } from "playwright";
import { writeFileSync, mkdirSync } from "fs";
import { BACKGROUNDS, MODIFIERS } from "../src/content/index.js";

const TEXT_SIZES = [
  { key: "sm", px: 11, weight: 400 },
  { key: "md", px: 13, weight: 600 },
  { key: "lg", px: 17, weight: 700 },
];
const EMOJI_PX = 20;
const ASCII = Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i));

// Emoji the card draws that aren't attached to a background or a trait.
const EXTRA = ["🧬"]; // the breed's own scoring row

const emoji = [...new Set([
  ...BACKGROUNDS.map((b) => b.emoji),
  ...MODIFIERS.map((m) => m.emoji),
  ...EXTRA,
])];

const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await browser.newPage();

// --- text: white on transparent, stored as alpha only so it can be tinted at blit time ---
const text = {};
for (const size of TEXT_SIZES) {
  const baked = await page.evaluate(
    ({ chars, px, weight }) => {
      const pad = 2;
      const cell = Math.ceil(px * 2) + pad * 2;
      const c = document.createElement("canvas");
      c.width = cell * chars.length;
      c.height = cell;
      const x = c.getContext("2d");
      x.font = `${weight} ${px}px "DejaVu Sans", sans-serif`;
      x.textBaseline = "alphabetic";
      x.fillStyle = "#fff";

      const baseline = Math.round(cell * 0.62);
      const widths = chars.map((ch, i) => {
        x.fillText(ch, i * cell + pad, baseline);
        return x.measureText(ch).width;
      });

      const d = x.getImageData(0, 0, c.width, c.height).data;
      const alpha = new Array(c.width * c.height);
      for (let i = 0; i < alpha.length; i++) alpha[i] = d[i * 4 + 3];
      return { cell, pad, baseline, widths, alpha, w: c.width, h: c.height };
    },
    { chars: ASCII, px: size.px, weight: size.weight }
  );

  text[size.key] = {
    px: size.px,
    cell: baked.cell,
    pad: baked.pad,
    baseline: baked.baseline,
    widths: baked.widths.map((w) => Math.round(w * 100) / 100),
    w: baked.w,
    h: baked.h,
    alpha: Buffer.from(Uint8Array.from(baked.alpha)).toString("base64"),
  };
  console.log(`text ${size.key} (${size.px}px/${size.weight}): ${baked.w}x${baked.h}`);
}

// --- emoji: full colour, so RGBA ---
const bakedEmoji = await page.evaluate(
  ({ list, px }) => {
    const cell = px + 4;
    const c = document.createElement("canvas");
    c.width = cell * list.length;
    c.height = cell;
    const x = c.getContext("2d");
    x.font = `${px}px sans-serif`;
    x.textBaseline = "middle";
    x.textAlign = "center";
    list.forEach((e, i) => x.fillText(e, i * cell + cell / 2, cell / 2));
    return { cell, w: c.width, h: c.height, rgba: Array.from(x.getImageData(0, 0, c.width, c.height).data) };
  },
  { list: emoji, px: EMOJI_PX }
);

await browser.close();

const atlas = {
  text,
  emoji: {
    cell: bakedEmoji.cell,
    w: bakedEmoji.w,
    h: bakedEmoji.h,
    index: Object.fromEntries(emoji.map((e, i) => [e, i])),
    rgba: Buffer.from(Uint8Array.from(bakedEmoji.rgba)).toString("base64"),
  },
};

mkdirSync("src/generated", { recursive: true });
writeFileSync("src/generated/atlas.js", `// Generated by scripts/build-atlas.mjs -- do not edit by hand.\nexport default ${JSON.stringify(atlas)};\n`);

const kb = (JSON.stringify(atlas).length / 1024).toFixed(0);
console.log(`emoji: ${emoji.length} glyphs at ${EMOJI_PX}px -> ${bakedEmoji.w}x${bakedEmoji.h}`);
console.log(`wrote src/generated/atlas.js (${kb} KB)`);
