// Facts about its life and situation that have nothing to do with the dog itself.
//
// Tone: plain and dry. "Has malaria", not "cursed by ancient forces". The comedy is in
// stating a grim or absurd fact flatly next to a number.
//
// Visuals are declarative -- { type, layer, params } -- rendered by public/effects.js:
//   back    -- the world behind the dog
//   front   -- stuff between you and the dog
//   subject -- CSS on the photo itself, so the effect visibly touches the animal
//
// Never delete a trait. Mark it `obsolete: true` -- stored dogs still reference theirs.

export const CIRCUMSTANCE = [
  // ----- civic life -----
  { text: "Votes", emoji: "🗳️", value: 1, category: "circumstance", effect: null },
  { text: "Has strong opinions about the bin collection", emoji: "🗑️", value: 1, category: "circumstance", effect: null },
  { text: "Attended one protest. Unclear which side.", emoji: "📣", value: 0, category: "circumstance", effect: null },
  { text: "Served on a jury", emoji: "👨‍⚖️", value: 2, category: "circumstance", effect: null },
  { text: "Banned from the community group chat", emoji: "💬", value: -1, category: "circumstance", effect: null },

  // ----- the machine -----
  { text: "In an AI training set", emoji: "🤖", value: 2, category: "circumstance",
    effect: { type: "glitch", layer: "front", params: { color: "#38bdf8", intensity: 0.25, scanlines: true } } },
  { text: "Wearing a GPS collar he has defeated", emoji: "📡", value: -1, category: "circumstance", effect: null },
  { text: "Smart collar reports him to you", emoji: "🔔", value: -1, category: "circumstance", effect: null },
  { text: "Has been mistaken for a robot", emoji: "⚙️", value: -1, category: "circumstance",
    effect: { type: "chromatic", layer: "subject", params: { offset: 2 } } },

  { text: "Owns nothing", emoji: "🫙", value: -1, category: "circumstance", group: "money", effect: null },
  { text: "Paying off a mortgage", emoji: "🏚️", value: -2, category: "circumstance", group: "money", effect: null },
  { text: "Ignored by everyone", emoji: "🫥", value: -1, category: "circumstance", group: "fame",
    effect: { type: "ghost", layer: "subject", params: { opacity: 0.8 } } },
  { text: "Night shift security", emoji: "🔦", value: -1, category: "circumstance", group: "job",
    effect: { type: "spotlight", layer: "front", params: { color: "#e5e7eb", radius: 110, speed: 0.9 } } },
  { text: "Unpaid intern", emoji: "☕", value: -2, category: "circumstance", group: "job", effect: null },
  { text: "Same house since birth", emoji: "🏡", value: 3, category: "circumstance", group: "homes", effect: null },
  { text: "Was a gift. Unwanted.", emoji: "🎁", value: -3, category: "circumstance", group: "homes",
    effect: { type: "vignette", layer: "front", params: { color: "#1c1917", opacity: 0.45 } } },

  // ----- money: one financial situation per dog -----
  { text: "Trust fund", emoji: "💰", value: 5, category: "circumstance", group: "money",
    effect: { type: "fall", layer: "front", params: { color: "#fbbf24", shape: "dot", count: 20, speed: 1.1, sway: 1.2, size: 4 } } },
  { text: "In debt", emoji: "📉", value: -3, category: "circumstance", group: "money",
    effect: { type: "vignette", layer: "front", params: { color: "#1c1917", opacity: 0.5 } } },
  { text: "Has a pension, somehow", emoji: "🏦", value: 4, category: "circumstance", group: "money", effect: null },

  // ----- fame: one kind of being known -----
  { text: "Briefly famous online", emoji: "📱", value: 2, category: "circumstance", group: "fame",
    effect: { type: "burst", layer: "front", params: { color: "#bef264", count: 18, spread: 120 } } },
  { text: "Has a Wikipedia page", emoji: "📖", value: 5, category: "circumstance", group: "fame",
    effect: { type: "rays", layer: "back", params: { color: "#fef08a", beams: 10, opacity: 0.3, speed: 0.07 } } },
  { text: "Known to police", emoji: "🚓", value: -4, category: "circumstance", group: "fame",
    effect: { type: "lightning", layer: "front", params: { color: "#93c5fd", frequency: 0.012 } } },

  { text: "Owns the house. Legally.", emoji: "🏠", value: 6, category: "circumstance",
    effect: { type: "spotlight", layer: "front", params: { color: "#fef3c7", radius: 140, speed: 0.3 } } },
  { text: "Has a restraining order", emoji: "⛔", value: -5, category: "circumstance",
    effect: { type: "vignette", layer: "front", params: { color: "#450a0a", opacity: 0.55 } } },

  { text: "Owner is getting divorced", emoji: "💔", value: -5, category: "circumstance",
    effect: { type: "drain", layer: "subject", params: { amount: 0.5 } } },
  { text: "Rehomed twice", emoji: "📦", value: -2, category: "circumstance", group: "homes", effect: null },
  { text: "Was on the news once", emoji: "📺", value: 3, category: "circumstance", group: "fame",
    effect: { type: "spotlight", layer: "front", params: { color: "#fef08a", radius: 130, speed: 0.6 } } },
  { obsolete: true, text: "Lives in a studio apartment", emoji: "🏢", value: -2, category: "circumstance", effect: null },
  { text: "Has a better bed than you", emoji: "🛏️", value: 2, category: "circumstance", effect: null },
  { text: "Named after the owner's ex", emoji: "✏️", value: -1, category: "circumstance", effect: null },
  { obsolete: true, text: "Inherited, along with the house", emoji: "🏚️", value: 1, category: "circumstance", effect: null },
  { text: "Four owners deep", emoji: "🔁", value: -2, category: "circumstance", group: "homes",
    effect: { type: "ghost", layer: "subject", params: { opacity: 0.7 } } },
  { text: "Has a LinkedIn", emoji: "💼", value: 2, category: "circumstance",
    effect: { type: "spotlight", layer: "front", params: { color: "#38bdf8", radius: 120, speed: 0.4 } } },
  { text: "Named in a lawsuit", emoji: "⚖️", value: -5, category: "circumstance",
    effect: { type: "glitch", layer: "front", params: { color: "#f87171", intensity: 0.35, scanlines: true } } },
  { text: "Won something in 2019", emoji: "🏆", value: 2, category: "circumstance",
    effect: { type: "burst", layer: "front", params: { color: "#fbbf24", count: 30, spread: 150, confetti: true } } },
  { text: "Has never seen grass", emoji: "🏢", value: -5, category: "circumstance",
    effect: { type: "drain", layer: "subject", params: { amount: 0.6 } } },
  { text: "Has a nemesis", emoji: "😾", value: -5, category: "circumstance", effect: null },
  { text: "Has been to Paris", emoji: "🗼", value: 2, category: "circumstance",
    effect: { type: "rays", layer: "back", params: { color: "#fcd34d", beams: 8, opacity: 0.26, speed: 0.09 } } },
  { text: "Is the reason for the no-dogs rule", emoji: "🚷", value: -5, category: "circumstance",
    effect: { type: "glitch", layer: "front", params: { color: "#fb923c", intensity: 0.4, scanlines: false } } },
  { text: "Appears in a stranger's wedding photos", emoji: "💒", value: 2, category: "circumstance",
    effect: { type: "burst", layer: "front", params: { color: "#fbcfe8", count: 26, spread: 140 } } },
  { text: "Under investigation", emoji: "🔍", value: -5, category: "circumstance",
    effect: { type: "spotlight", layer: "front", params: { color: "#e5e7eb", radius: 110, speed: 0.9 } } },
  { text: "Outlived two previous owners", emoji: "🕰️", value: -2, category: "circumstance", group: "homes",
    effect: { type: "ghost", layer: "subject", params: { opacity: 0.75 } } },
  { text: "First time homeowner", emoji: "🏡", value: 2, category: "circumstance",
    effect: { type: "vignette", layer: "front", params: { color: "#78350f", opacity: 0.35 } } },
  { text: "Megacorporation CEO", emoji: "💼", value: 6, category: "circumstance", group: "job",
    effect: { type: "rays", layer: "back", params: { color: "#fcd34d", beams: 8, opacity: 0.3, speed: 0.08 } } },
  { text: "Supreme Court Justice", emoji: "⚖️", value: 7, category: "circumstance", group: "job",
    effect: { type: "spotlight", layer: "front", params: { color: "#fef3c7", radius: 140, speed: 0.3 } } },
  { text: "Frog Wars veteran", emoji: "🐸", value: 2, category: "circumstance",
    effect: { type: "fall", layer: "front", params: { color: "#4ade80", shape: "dot", count: 22, speed: 0.8, sway: 2.4, size: 5 } } },
  { text: "Rick and Morty superfan", emoji: "🛸", value: -5, category: "circumstance",
    effect: { type: "glitch", layer: "front", params: { color: "#4ade80", intensity: 0.5, scanlines: true } } },
  { text: "Unemployed", emoji: "🛌", value: -2, category: "circumstance", group: "job", effect: null },
  { text: "Raised in a puppy mill", emoji: "🏭", value: -6, category: "circumstance",
    effect: { type: "drain", layer: "subject", params: { amount: 0.75 } } },
  { text: "Dogdle developer", emoji: "👨‍💻", value: 5, category: "circumstance", group: "job",
    effect: { type: "halo", layer: "subject", params: { color: "#22d3ee", size: 14 } } },
  { text: "Local celebrity", emoji: "👑", value: 6, category: "circumstance", group: "fame",
    effect: { type: "spotlight", layer: "front", params: { color: "#fde047", radius: 135, speed: 0.45 } } },
  { text: "Banned from one (1) country", emoji: "🚨", value: -5, category: "circumstance",
    effect: { type: "lightning", layer: "front", params: { color: "#fca5a5", frequency: 0.008 } } },
  { text: "Survived something from space", emoji: "☄️", value: 7, category: "circumstance",
    effect: { type: "rise", layer: "front", params: { color: "#fb923c", count: 30, speed: 1.3, sway: 2, size: 4, glow: true } } },
  { text: "Birthday today", emoji: "🎂", value: 2, category: "circumstance",
    effect: { type: "burst", layer: "front", params: { color: "#f472b6", count: 30, spread: 150, confetti: true } } },
  { text: "Raised by ducks", emoji: "🦆", value: 2, category: "circumstance",
    effect: { type: "fall", layer: "front", params: { color: "#fef9c3", shape: "petal", count: 16, speed: 0.6, sway: 2, size: 4 } } },
  { text: "Best friends with a horse", emoji: "🐴", value: 2, category: "circumstance", effect: null },
  { text: "Owes a crow money", emoji: "🐦", value: -3, category: "circumstance", effect: null },
  { text: "Tried to eat a hedgehog. Lost.", emoji: "🦔", value: -3, category: "circumstance", effect: null },
  { text: "One specific squirrel", emoji: "🐿️", value: -1, category: "circumstance", effect: null },
  { text: "Beat the robot vacuum in single combat", emoji: "🤖", value: 2, category: "circumstance", effect: null },
  { text: "Butt-dialled 911", emoji: "📞", value: -2, category: "circumstance",
    effect: { type: "pulse", layer: "back", params: { color: "#ef4444", period: 900, radius: 160 } } },
  { text: "Alexa takes his orders. Forty tennis balls so far.", emoji: "🔊", value: -5, category: "circumstance",
    effect: { type: "ripple", layer: "back", params: { color: "#22d3ee", rings: 3, speed: 1, maxRadius: 150 } } },
  { text: "Sponsored by a treat brand", emoji: "💸", value: 4, category: "circumstance", group: "money",
    effect: { type: "spotlight", layer: "front", params: { color: "#fde68a", radius: 110, speed: 0.8 } } },
  { text: "Paintings sell for $400", emoji: "🎨", value: 2, category: "circumstance", effect: null },
  { text: "Has an agent. No bookings.", emoji: "🎭", value: -1, category: "circumstance", effect: null },
  { text: "Ate a library book. Chapter seven specifically.", emoji: "📚", value: -3, category: "circumstance",
    effect: { type: "fall", layer: "front", params: { color: "#f5f5f4", shape: "square", count: 18, speed: 0.9, sway: 1.4, size: 5 } } },
  { text: "Reincarnated from your grandmother", emoji: "♾️", value: 2, category: "circumstance",
    effect: { type: "halo", layer: "subject", params: { color: "#e9d5ff", size: 12 } } },
  { text: "Has a girlfriend across the street", emoji: "💌", value: 2, category: "circumstance",
    effect: { type: "rise", layer: "front", params: { color: "#f472b6", shape: "heart", count: 12, speed: 0.7, sway: 1.5, size: 10 } } },
  { text: "Dumped by a poodle", emoji: "💔", value: -2, category: "circumstance",
    effect: { type: "fall", layer: "front", params: { color: "#93c5fd", shape: "line", count: 30, speed: 2, sway: 0, size: 8 } } },
  { text: "Invited to every birthday party", emoji: "🎉", value: 2, category: "circumstance",
    effect: { type: "burst", layer: "front", params: { color: "#60a5fa", count: 26, spread: 140, confetti: true } } },
  { text: "Uninvited from Thanksgiving", emoji: "🦃", value: -4, category: "circumstance", effect: null },
  { text: "Pulled a child from a lake", emoji: "🛟", value: 7, category: "circumstance",
    effect: { type: "rays", layer: "back", params: { color: "#fef08a", beams: 10, opacity: 0.3, speed: 0.07 } } },
  { text: "Found a gas leak", emoji: "🧯", value: 2, category: "circumstance", effect: null },
  { text: "Retired airport drug dog. Knows things.", emoji: "🛃", value: 3, category: "circumstance", group: "job",
    effect: { type: "spotlight", layer: "front", params: { color: "#e5e7eb", radius: 100, speed: 1 } } },
  { text: "Dishonourably discharged from the K-9 unit", emoji: "🪖", value: -4, category: "circumstance", group: "job",
    effect: { type: "drain", layer: "subject", params: { amount: 0.5 } } },
  { text: "Guarded a grave for fourteen years. Wrong grave.", emoji: "🪦", value: -1, category: "circumstance",
    effect: { type: "fog", layer: "front", params: { color: "#94a3b8", bands: 2, opacity: 0.3, speed: 0.4 } } },
  { text: "Bit an elephant on the lip. For you.", emoji: "🐘", value: 4, category: "circumstance", effect: null },
  { text: "Won a trial by combat", emoji: "⚔️", value: 6, category: "circumstance",
    effect: { type: "burst", layer: "front", params: { color: "#e5e7eb", count: 18, spread: 120 } } },
  { text: "Walked 2,500 miles home. You'd moved.", emoji: "🗺️", value: -3, category: "circumstance",
    effect: { type: "tint", layer: "subject", params: { sepia: 0.5, hue: 0, saturate: 0.9 } } },
  { text: "Has a statue somewhere", emoji: "🏛️", value: 4, category: "circumstance", group: "fame", effect: null },
  { text: "Former witch's familiar. Took early retirement.", emoji: "🧹", value: 1, category: "circumstance",
    effect: { type: "rise", layer: "front", params: { color: "#a78bfa", count: 12, speed: 0.6, sway: 1.8, size: 3, glow: true } } },
  { text: "Has his own constellation", emoji: "🌌", value: 6, category: "circumstance",
    effect: { type: "stars", layer: "back", params: { color: "#ffffff", count: 70, twinkle: 0.6 } } },
  { text: "Followed a stranger home. They're lucky now.", emoji: "🐾", value: 2, category: "circumstance", effect: null },
  { text: "Anti-poaching paratrooper", emoji: "🪂", value: 6, category: "circumstance", group: "job", effect: null },
  { text: "Has lived this day before", emoji: "📆", value: -3, category: "circumstance",
    effect: { type: "glitch", layer: "front", params: { color: "#94a3b8", intensity: 0.2, scanlines: true } } },
  { text: "Has seen the edge of the map", emoji: "🌐", value: 4, category: "circumstance", effect: null },
  { text: "Birds land on him to rest", emoji: "🕊️", value: 2, category: "circumstance", effect: null },
  { text: "Named in a poem that was never published", emoji: "📝", value: 1, category: "circumstance", effect: null },
  { text: "Tangled in a thread that leads somewhere", emoji: "🧵", value: -1, category: "circumstance", effect: null },
  { text: "The stars are right", emoji: "⭐", value: 6, category: "circumstance",
    effect: { type: "stars", layer: "back", params: { color: "#ffffff", count: 80, twinkle: 0.7 } } },
  { text: "Stared into the abyss. The abyss looked away first.", emoji: "🌚", value: 2, category: "circumstance",
    effect: { type: "vignette", layer: "front", params: { color: "#000000", opacity: 0.55 } } },
  { text: "Guards a door that must stay shut", emoji: "🔒", value: 2, category: "circumstance", effect: null },
  { text: "Worshipped by a small, damp cult", emoji: "🗿", value: 2, category: "circumstance", group: "fame", effect: null },
  { text: "Solves mysteries, mostly by accident", emoji: "🕵️", value: 2, category: "circumstance",
    effect: { type: "spotlight", layer: "front", params: { color: "#fef9c3", radius: 100, speed: 1 } } },
  { text: "Flies his doghouse against the Red Baron", emoji: "🛩️", value: 3, category: "circumstance", effect: null },
  { text: "No rule says he can't play basketball", emoji: "🏀", value: 2, category: "circumstance", effect: null },
  { text: "Such dog. Very wow.", emoji: "🪙", value: 2, category: "circumstance", effect: null },
  { text: "Haunts a moor in Devon", emoji: "🌾", value: -3, category: "circumstance",
    effect: { type: "fog", layer: "front", params: { color: "#a3a3a3", bands: 3, opacity: 0.35, speed: 0.4 } } },
  { text: "Knits, reads, and does all the actual work", emoji: "🧀", value: 3, category: "circumstance", effect: null },
  { text: "Pulled back the curtain on a wizard", emoji: "🌪️", value: 2, category: "circumstance", effect: null },
  { text: "Someone hurt his predecessor. They regret it.", emoji: "🕴️", value: 2, category: "circumstance",
    effect: { type: "vignette", layer: "front", params: { color: "#111827", opacity: 0.4 } } },
  { text: "World's worst dog, per a bestseller", emoji: "📗", value: -3, category: "circumstance", effect: null },
  { text: "Knows who let the dogs out. Won't say.", emoji: "🎶", value: 1, category: "circumstance", effect: null },
  { text: "Housebroken at gunpoint", emoji: "🎯", value: 0, category: "circumstance", effect: null },
  { text: "Knows who the father is. Keeping it to himself.", emoji: "🤫", value: 1, category: "circumstance", effect: null },
  { text: "Looks frightening. Very popular with women.", emoji: "💐", value: 2, category: "circumstance", effect: null },
  { text: "Can be petted. Reviewers will mention it.", emoji: "🎮", value: 1, category: "circumstance", effect: null },
  { text: "Once travelled one minute into the future", emoji: "⏰", value: 1, category: "circumstance",
    effect: { type: "glitch", layer: "front", params: { color: "#f97316", intensity: 0.2, scanlines: false } } },
  { text: "Briefly ran the Moscow department of cats", emoji: "🐈‍⬛", value: -1, category: "circumstance", effect: null },
  { text: "Arrived at the base chased by a helicopter", emoji: "🚁", value: -3, category: "circumstance",
    effect: { type: "fall", layer: "front", params: { color: "#f8fafc", shape: "dot", count: 40, speed: 1.6, sway: 2.8, size: 3 } } },
  { text: "Stopped a library break-in. It smelled wrong.", emoji: "🕯️", value: 3, category: "circumstance", effect: null },
  { text: "Wants his jade amulet back", emoji: "💎", value: -2, category: "circumstance", effect: null },
  { text: "Brought you the Yellow Sign. Good boy.", emoji: "🟨", value: -3, category: "circumstance",
    effect: { type: "tint", layer: "subject", params: { sepia: 0.6, hue: 15, saturate: 1.8 } } },
  { text: "One bark, remixed into every song ever", emoji: "🎵", value: 1, category: "circumstance", group: "fame",
    effect: { type: "ripple", layer: "back", params: { color: "#a78bfa", rings: 4, speed: 1.6, maxRadius: 170 } } },
  { text: "Three-time World's Ugliest. Retired undefeated.", emoji: "🥴", value: 1, category: "circumstance", group: "fame", effect: null },
  { text: "Rated 12/10. Brent had concerns.", emoji: "💯", value: 1, category: "circumstance", group: "fame", effect: null },
  { text: "Ambushed Napoleon with rabbits", emoji: "🐇", value: 1, category: "circumstance", effect: null },
  { text: "Grandma survived the Titanic", emoji: "🚢", value: 2, category: "circumstance", group: "pedigree", effect: null },
  { text: "Deserted a Roman legion", emoji: "⚔️", value: -1, category: "circumstance", effect: null },
  { text: "On a Greek vase, badly drawn", emoji: "🏺", value: -1, category: "circumstance", effect: null },
  { text: "Pawprinted the Magna Carta", emoji: "📜", value: 1, category: "circumstance", effect: null },
  { text: "Guarded a castle. It fell.", emoji: "🏰", value: -2, category: "circumstance", effect: null },
  { text: "Still honours a caveman's deal", emoji: "🔥", value: 1, category: "circumstance", group: "pedigree", effect: null },
  { text: "Cloned from the wrong famous dog", emoji: "🧬", value: -2, category: "circumstance", group: "pedigree", effect: null },
  { text: "Born in space. Never seen grass.", emoji: "🛸", value: -2, category: "circumstance", effect: null },
  { text: "Frozen in 2026. Thawed early.", emoji: "🧊", value: -1, category: "circumstance",
    effect: { type: "tint", layer: "subject", params: { sepia: 0.2, hue: 180, saturate: 0.7 } } },
  { text: "Sent back in time to protect you", emoji: "⏳", value: 2, category: "circumstance",
    effect: { type: "lightning", layer: "front", params: { color: "#bfdbfe", frequency: 0.02 } } },
  { text: "Backed up to the cloud. Twice.", emoji: "💾", value: 1, category: "circumstance", effect: null },
  { text: "First dog in orbit", emoji: "🛰️", value: 4, category: "circumstance",
    effect: { type: "rise", layer: "back", params: { color: "#e0e7ff", count: 16, speed: 0.3, sway: 0.4, size: 2 } } },
  { text: "Owes the mob a tennis ball", emoji: "🎾", value: -2, category: "circumstance", effect: null },
  { text: "Filed his own taxes. Owes.", emoji: "🧾", value: -2, category: "circumstance", effect: null },
  { text: "Elected mayor. Ran unopposed.", emoji: "🎗️", value: 4, category: "circumstance", effect: null },
  { text: "In a situationship with the neighbor's cat", emoji: "🐈", value: -1, category: "circumstance", effect: null },
  { text: "Emotional support human", emoji: "🫂", value: 2, category: "circumstance", effect: null },
  // The writers' room, round one: five angles, three reviewers, fifty keepers.
  { text: "Chases cars. Caught one. Kept it.", emoji: "🚗", value: 2, category: "circumstance", effect: null },
  { text: "Came back from camping alone", emoji: "🔦", value: -3, category: "circumstance", effect: null },
  { text: "Has a second family in Leeds", emoji: "🏠", value: -3, category: "circumstance", effect: null },
  { text: "His vet file is sealed by a court", emoji: "⚖️", value: -3, category: "circumstance", effect: null },
  { text: "Found the stolen World Cup in a hedge", emoji: "🏆", value: 4, category: "circumstance", effect: null },
  { text: "Ring bearer. The ring is gone.", emoji: "💍", value: -2, category: "circumstance", effect: null },
  { text: "Won the marathon. Took the subway.", emoji: "🚇", value: -3, category: "circumstance", effect: null },
  { text: "Daughter's a cop. They don't talk.", emoji: "🚓", value: -1, category: "circumstance", effect: null },
  { text: "Fell down a hole. Found Lascaux.", emoji: "🦬", value: 2, category: "circumstance", effect: null },
  { text: "Exited, pursued by a bear", emoji: "🐻", value: -1, category: "circumstance", effect: null },
  { text: "Missed the Ark. Swam.", emoji: "🌊", value: 2, category: "circumstance", effect: null },
  { text: "Buried his seed phrase. Lost it.", emoji: "🔑", value: -4, category: "circumstance", effect: null },
  { text: "Is your lock screen", emoji: "🔒", value: 3, category: "circumstance", effect: null },
  { text: "Is a landlord", emoji: "🏘️", value: -3, category: "circumstance", effect: null },
  { text: "Two Patreon backers. Both you.", emoji: "💳", value: -1, category: "circumstance", effect: null },
  { text: "Named in a will. Not as the dog.", emoji: "📜", value: 3, category: "circumstance", effect: null },
  { text: "Ohio still sets a place for him", emoji: "🍽️", value: 2, category: "circumstance", effect: null },
  // The boring writers' room: extremely mundane, some suspiciously so.
  { text: "Has never been in the shed", emoji: "🔒", value: -1, category: "circumstance", effect: null },
  { text: "Fence was already like that", emoji: "🚧", value: -2, category: "circumstance", effect: null },
  { text: "Nothing happened on Tuesday", emoji: "📅", value: -1, category: "circumstance", effect: null },
  { text: "Was at Dave's. Ask Dave.", emoji: "🍕", value: 0, category: "circumstance", effect: null },
  { text: "Never seen that man before", emoji: "🤷", value: -1, category: "circumstance", effect: null },
  { text: "Was not near the lake", emoji: "🦆", value: -1, category: "circumstance", effect: null },
  { text: "Nothing to declare", emoji: "🛃", value: -1, category: "circumstance", effect: null },
  { text: "N/A", emoji: "📋", value: -1, category: "circumstance", effect: null },
  { text: "Present", emoji: "✋", value: 1, category: "circumstance", effect: null },
  { text: "Just a dog, officer", emoji: "👮", value: -1, category: "circumstance", effect: null },
  { text: "No priors", emoji: "📁", value: 1, category: "circumstance", effect: null },
  // The trait tournament, round 1: picked by a human from ten writers' best.
  { text: "Microchip registered to a stranger", emoji: "🔖", value: -2, category: "circumstance", effect: null },
  { text: "Left on read by the vet", emoji: "💬", value: -1, category: "circumstance", effect: null },
  { text: "Still paying for a streaming service he forgot", emoji: "📺", value: -2, category: "circumstance", effect: null },
  { text: "Has never once been audited", emoji: "🧾", value: 2, category: "circumstance", effect: null },
  { text: "Godfather to a goose", emoji: "🪿", value: 1, category: "circumstance", effect: null },
  // The trait tournament, round 2.
  { text: "Reward offered: $5, negotiable", emoji: "💵", value: -2, category: "circumstance", effect: null },
  { text: "Listed as next of kin. Twice.", emoji: "🪪", value: 2, category: "circumstance", effect: null },
  { text: "Was returned once. Nobody mentions it.", emoji: "📦", value: -3, category: "circumstance", effect: null },
  { text: "Matched with a wolf. Got ghosted.", emoji: "🐺", value: -2, category: "circumstance", effect: null },
  { text: "Second-best dog on the Christmas card", emoji: "🎄", value: -1, category: "circumstance", effect: null },
  { text: "Ran away once. Sent a postcard.", emoji: "📮", value: 1, category: "circumstance", effect: null },
  { text: "Survived the fire. Started it.", emoji: "🔥", value: -3, category: "circumstance", effect: null },
  { text: "Co-signed a loan for a raccoon", emoji: "🦝", value: -3, category: "circumstance", effect: null },
  { text: "Signed up for a free trial in 2019", emoji: "💳", value: -2, category: "circumstance", effect: null },
  { text: "Neighbours have a photo of him from 1974", emoji: "🖼️", value: 0, category: "circumstance", effect: null },
  { text: "Has a timeshare in a town that flooded", emoji: "🏖️", value: -2, category: "circumstance", effect: null },
  { text: "Next of kin: a parrot", emoji: "🦜", value: -1, category: "circumstance", effect: null },
  { text: "Was the getaway driver", emoji: "🚙", value: -1, category: "circumstance", effect: null },
];
