// The state it happens to be in: wearing something, covered in something,
// or quietly violating physics.
//
// Tone: plain and dry. "Has malaria", not "cursed by ancient forces". The comedy is in
// stating a grim or absurd fact flatly next to a number.
//
// Visuals are declarative -- { type, layer, params } -- rendered by public/effects.js:
//   back    -- the world behind the dog
//   front   -- stuff between you and the dog
//   subject -- CSS on the photo itself, so the effect visibly touches the animal
//
// Never delete a trait. Mark it `obsolete: true` -- stored dogs still reference theirs.

export const CONDITION = [
  // ----- coat: the fur itself, which the table had never once mentioned -----
  { text: "Sheds catastrophically", emoji: "🧹", value: -3, category: "condition", group: "coat",
    effect: { type: "rise", layer: "front", params: { color: "#e5e7eb", count: 26, speed: 0.6, sway: 3, size: 3 } } },
  { text: "Hypoallergenic, allegedly", emoji: "🤧", value: 1, category: "condition", group: "coat", effect: null },
  { text: "Permanently matted", emoji: "🪢", value: -3, category: "condition", group: "coat",
    effect: { type: "blur", layer: "subject", params: { amount: 1 } } },
  { text: "A colour not found in the breed standard", emoji: "🎨", value: 1, category: "condition", group: "coat",
    effect: { type: "tint", layer: "subject", params: { sepia: 0.3, hue: 200, saturate: 1.4 } } },
  { text: "Coat changes in winter", emoji: "🧥", value: 1, category: "condition", group: "coat", effect: null },

  { text: "Unwashed", emoji: "🧼", value: -3, category: "condition", group: "smell",
    effect: { type: "tint", layer: "subject", params: { sepia: 0.3, hue: 20, saturate: 0.85 } } },
  { text: "Smells of the sea", emoji: "🐚", value: 1, category: "condition", group: "smell", effect: null },
  { text: "Deceptively heavy", emoji: "⚖️", value: 0, category: "condition", group: "build", effect: null },
  { text: "Built like a brick", emoji: "🏗️", value: 1, category: "condition", group: "build",
    effect: { type: "squish", layer: "subject", params: { period: 1900 } } },
  { text: "Photogenic, annoyingly", emoji: "📸", value: 3, category: "condition", group: "camera",
    effect: { type: "burst", layer: "front", params: { color: "#e5e7eb", count: 16, spread: 110 } } },

  // ----- build: a dog is one shape, so only one of these can land -----
  { text: "Morbidly obese", emoji: "🍔", value: -4, category: "condition", group: "build",
    effect: { type: "squish", layer: "subject", params: { period: 1400 } } },
  { text: "Anorexic", emoji: "🪶", value: -5, category: "condition", group: "build",
    effect: { type: "ghost", layer: "subject", params: { opacity: 0.75 } } },
  { text: "Starved", emoji: "🍽️", value: -5, category: "condition", group: "build",
    effect: { type: "drain", layer: "subject", params: { amount: 0.6 } } },
  { text: "Thick boy", emoji: "🧈", value: 2, category: "condition", group: "build",
    effect: { type: "bounce", layer: "subject", params: { period: 1200 } } },
  { text: "Grotesque figure", emoji: "👹", value: -4, category: "condition", group: "build",
    effect: { type: "chromatic", layer: "subject", params: { offset: 4 } } },
  { text: "Alarmingly long", emoji: "📏", value: -1, category: "condition", group: "build",
    effect: { type: "squish", layer: "subject", params: { period: 2600 } } },
  { text: "Concerningly small", emoji: "🔬", value: -2, category: "condition", group: "build", effect: null },
  { text: "Perfectly proportioned", emoji: "📐", value: 4, category: "condition", group: "build",
    effect: { type: "halo", layer: "subject", params: { color: "#ffffff", size: 10, brightness: 1.15 } } },

  // ----- smell: likewise, a dog smells of one thing -----
  { text: "Smells faintly of bread", emoji: "🍞", value: 2, category: "condition", group: "smell",
    effect: { type: "rise", layer: "front", params: { color: "#fcd34d", count: 14, speed: 0.5, sway: 2, size: 3 } } },

  { text: "Wearing a small hat", emoji: "🎩", value: 3, category: "condition", effect: null },
  { text: "Cone of shame", emoji: "🔺", value: -1, category: "condition",
    effect: { type: "fog", layer: "front", params: { color: "#94a3b8", bands: 2, opacity: 0.3, speed: 0.5 } } },
  { text: "Covered in mud", emoji: "🟤", value: -4, category: "condition",
    effect: { type: "fall", layer: "front", params: { color: "#78350f", shape: "dot", count: 40, speed: 1.4, sway: 1, size: 4.5 } } },
  { text: "Groomed this morning", emoji: "💈", value: 3, category: "condition",
    effect: { type: "halo", layer: "subject", params: { color: "#ffffff", size: 10, brightness: 1.15 } } },
  { text: "Smells, and everyone knows", emoji: "🤢", value: -3, category: "condition", group: "smell",
    effect: { type: "rise", layer: "front", params: { color: "#84cc16", count: 20, speed: 0.4, sway: 2.6, size: 4, glow: true } } },
  { text: "Wearing a sweater someone knitted", emoji: "🧶", value: 3, category: "condition",
    effect: { type: "fall", layer: "front", params: { color: "#fda4af", shape: "dot", count: 22, speed: 0.3, sway: 2, size: 4 } } },
  { text: "Soaking wet", emoji: "💧", value: -1, category: "condition",
    effect: { type: "fall", layer: "front", params: { color: "#93c5fd", shape: "line", count: 34, speed: 2.4, sway: 0, size: 10 } } },
  { text: "Surrounded by bees", emoji: "🐝", value: -4, category: "condition", effect: null },
  { text: "Slightly out of focus, always", emoji: "🌫️", value: -2, category: "condition", group: "camera",
    effect: { type: "blur", layer: "subject", params: { amount: 2.2 } } },
  { text: "Photographs badly", emoji: "📷", value: -1, category: "condition", group: "camera",
    effect: { type: "tint", layer: "subject", params: { sepia: 0.7, hue: 10, saturate: 1.8 } } },
  { text: "Glows faintly. Unexplained.", emoji: "🔮", value: 4, category: "condition",
    effect: { type: "halo", layer: "subject", params: { color: "#22d3ee", size: 18, brightness: 1.2 } } },
  { text: "Technically deceased", emoji: "⚰️", value: -6, category: "condition",
    effect: { type: "ghost", layer: "subject", params: { opacity: 0.45, blur: 1.2 } } },
  { text: "Statistically the luckiest dog alive", emoji: "🍀", value: 5, category: "condition",
    effect: { type: "burst", layer: "front", params: { color: "#4ade80", count: 44, spread: 200, confetti: true } } },
  { text: "Cannot be photographed properly", emoji: "📵", value: -2, category: "condition", group: "camera",
    effect: { type: "ghost", layer: "subject", params: { opacity: 0.6, blur: 1.4 } } },
  { text: "Smells like a hospital", emoji: "🏥", value: -2, category: "condition", group: "smell",
    effect: { type: "fog", layer: "front", params: { color: "#e0f2fe", bands: 3, opacity: 0.24, speed: 0.35 } } },
  { text: "Has a scar with a story", emoji: "🪡", value: 2, category: "condition", effect: null },
  { text: "One with nature", emoji: "🍃", value: 5, category: "condition",
    effect: { type: "rise", layer: "front", params: { color: "#86efac", count: 24, speed: 0.4, sway: 3, size: 6, shape: "leaf" } } },
  { text: "Devout Buddhist", emoji: "☸️", value: 6, category: "condition",
    effect: { type: "rays", layer: "back", params: { color: "#fde68a", beams: 12, opacity: 0.34, speed: 0.06, holy: true } } },
  { text: "Great at dog magic", emoji: "✨", value: 7, category: "condition",
    effect: { type: "halo", layer: "subject", params: { color: "#c084fc", size: 20, brightness: 1.15 } } },
  { text: "Somehow smells of cigarettes", emoji: "🚬", value: -3, category: "condition", group: "smell",
    effect: { type: "fog", layer: "front", params: { color: "#d6d3d1", bands: 3, opacity: 0.26, speed: 0.3 } } },
  { text: "Appears in two places at once", emoji: "🌀", value: 5, category: "condition",
    effect: { type: "chromatic", layer: "subject", params: { offset: 6 } } },
  { text: "No reflection", emoji: "🪞", value: -5, category: "condition",
    effect: { type: "ghost", layer: "subject", params: { opacity: 0.4, blur: 0.5 } } },
  // Age, pedigree, tail: each a thing a dog has exactly one of.
  { text: "Still a puppy, somehow, at nine", emoji: "🍼", value: 2, category: "condition", group: "age",
    effect: { type: "bounce", layer: "subject", params: { period: 900 } } },
  { text: "Grey muzzle. Very wise.", emoji: "👴", value: 3, category: "condition", group: "age",
    effect: { type: "drain", layer: "subject", params: { amount: 0.35 } } },
  { text: "Adolescent. The worst age.", emoji: "😤", value: -3, category: "condition", group: "age", effect: null },
  { text: "Vet guessed \"between two and eleven\"", emoji: "❓", value: 0, category: "condition", group: "age", effect: null },
  { text: "Grandfather won Westminster", emoji: "🏆", value: 4, category: "condition", group: "pedigree",
    effect: { type: "halo", layer: "subject", params: { color: "#fbbf24", size: 12 } } },
  { text: "Parents were siblings", emoji: "🧬", value: -5, category: "condition", group: "pedigree",
    effect: { type: "chromatic", layer: "subject", params: { offset: 3 } } },
  { text: "DNA test says eleven breeds, none of them this one", emoji: "🎲", value: -1, category: "condition", group: "pedigree",
    effect: { type: "glitch", layer: "front", params: { color: "#a78bfa", intensity: 0.2, scanlines: false } } },
  { text: "Papers are forged", emoji: "📜", value: -2, category: "condition", group: "pedigree",
    effect: { type: "tint", layer: "subject", params: { sepia: 0.7, hue: 0, saturate: 0.8 } } },
  { text: "No tail. Wags whole body.", emoji: "✂️", value: 2, category: "condition", group: "tail",
    effect: { type: "wobble", layer: "subject", params: { period: 350 } } },
  { text: "Tail clears coffee tables", emoji: "💥", value: -2, category: "condition", group: "tail",
    effect: { type: "burst", layer: "front", params: { color: "#d6d3d1", count: 16, spread: 130 } } },
  { text: "Only wags counter-clockwise. Vets intrigued.", emoji: "🔄", value: 1, category: "condition", group: "tail",
    effect: { type: "spin", layer: "subject", params: { period: 6000 } } },
  { text: "Has never wagged", emoji: "🫥", value: -3, category: "condition", group: "tail",
    effect: { type: "drain", layer: "subject", params: { amount: 0.4 } } },
  { text: "A different dog on full moons", emoji: "🌕", value: -4, category: "condition",
    effect: { type: "tint", layer: "subject", params: { sepia: 0.2, hue: 250, saturate: 0.6 } } },
  { text: "One ear up, one ear down", emoji: "👂", value: 2, category: "condition", effect: null },
  { text: "Has eyebrows. Uses them.", emoji: "🤨", value: 3, category: "condition", effect: null },
  { text: "Tongue permanently out", emoji: "👅", value: 1, category: "condition", effect: null },
  { text: "Underbite of a Bond villain", emoji: "🦷", value: -1, category: "condition", effect: null },
];
