// How it behaves toward people, other dogs, and the world.
//
// Tone: plain and dry. "Has malaria", not "cursed by ancient forces". The comedy is in
// stating a grim or absurd fact flatly next to a number.
//
// Visuals are declarative -- { type, layer, params } -- rendered by public/effects.js:
//   back    -- the world behind the dog
//   front   -- stuff between you and the dog
//   subject -- CSS on the photo itself, so the effect visibly touches the animal
//
// Never delete a trait. Mark it `obsolete: true` -- stored dogs still reference theirs.

export const TEMPERAMENT = [
  // ----- voice: a dog makes one noise -----
  { text: "Silent. Entirely.", emoji: "🤐", value: -2, category: "temperament", group: "voice", effect: null },
  { text: "One bark, saved for emergencies", emoji: "📢", value: 3, category: "temperament", group: "voice", effect: null },
  { text: "Barks in a different accent", emoji: "🗣️", value: 2, category: "temperament", group: "voice", effect: null },
  { text: "Voice cracks", emoji: "🎤", value: -1, category: "temperament", group: "voice", effect: null },

  // ----- weather: every dog has exactly one opinion about the sky -----
  { text: "Built for snow", emoji: "❄️", value: 2, category: "temperament", group: "weather",
    effect: { type: "fall", layer: "front", params: { color: "#ffffff", shape: "dot", count: 34, speed: 0.7, sway: 2.2, size: 3 } } },
  { text: "Refuses to go out in rain", emoji: "🌧️", value: -2, category: "temperament", group: "weather",
    effect: { type: "fall", layer: "front", params: { color: "#93c5fd", shape: "line", count: 40, speed: 2.4, sway: 0.3, size: 7 } } },
  { text: "Overheats immediately", emoji: "🥵", value: -2, category: "temperament", group: "weather",
    effect: { type: "tint", layer: "subject", params: { sepia: 0.2, hue: 350, saturate: 1.3 } } },
  { text: "Terrified of fireworks", emoji: "🎆", value: -3, category: "temperament", group: "weather",
    effect: { type: "burst", layer: "front", params: { color: "#fbcfe8", count: 26, spread: 140 } } },
  { text: "Unbothered by anything the sky does", emoji: "🌤️", value: 3, category: "temperament", group: "weather", effect: null },

  { text: "Average intelligence. Truly average.", emoji: "📊", value: 0, category: "temperament", group: "mind", effect: null },
  { text: "Cunning", emoji: "🦊", value: 3, category: "temperament", group: "mind",
    effect: { type: "chromatic", layer: "subject", params: { offset: 2 } } },
  { text: "Loyal to the concept of food", emoji: "🥓", value: -1, category: "temperament", group: "loyalty", effect: null },
  { text: "Would die for you, but reluctantly", emoji: "😒", value: 3, category: "temperament", group: "loyalty", effect: null },
  { text: "Refuses to fetch", emoji: "🙅", value: -2, category: "temperament", group: "fetch", effect: null },
  { text: "Fetches. Keeps it.", emoji: "🤲", value: -1, category: "temperament", group: "fetch", effect: null },
  { text: "Perfectly trained", emoji: "🎖️", value: 5, category: "temperament", group: "training",
    effect: { type: "halo", layer: "subject", params: { color: "#4ade80", size: 12 } } },
  { text: "Untrainable", emoji: "🤷", value: -3, category: "temperament", group: "training", effect: null },

  // ----- mind: one assessment of what is going on in there -----
  { text: "Genuinely stupid", emoji: "🪨", value: -3, category: "temperament", group: "mind",
    effect: { type: "blur", layer: "subject", params: { amount: 1 } } },
  { text: "Alarmingly clever", emoji: "🧠", value: 4, category: "temperament", group: "mind",
    effect: { type: "halo", layer: "subject", params: { color: "#38bdf8", size: 12 } } },

  // ----- loyalty: a dog is devoted to exactly one thing, or nothing -----
  { text: "Would die for you", emoji: "🛡️", value: 6, category: "temperament", group: "loyalty",
    effect: { type: "halo", layer: "subject", params: { color: "#4ade80", size: 12 } } },
  { text: "Would not die for you", emoji: "🏃", value: -2, category: "temperament", group: "loyalty", effect: null },
  { text: "Loyal to someone else", emoji: "💔", value: -3, category: "temperament", group: "loyalty",
    effect: { type: "drain", layer: "subject", params: { amount: 0.5 } } },

  { text: "Certified therapy dog", emoji: "🪪", value: 5, category: "temperament", group: "job",
    effect: { type: "pulse", layer: "back", params: { color: "#4ade80", period: 2600, radius: 190 } } },
  { text: "Likes everyone immediately", emoji: "🥰", value: 2, category: "temperament",
    effect: { type: "rise", layer: "front", params: { color: "#fb7185", count: 18, speed: 0.5, sway: 1.8, size: 9, shape: "heart" } } },
  { text: "Comes when called, every time", emoji: "📣", value: 4, category: "temperament", group: "training",
    effect: { type: "halo", layer: "subject", params: { color: "#38bdf8", size: 10 } } },
  { obsolete: true, text: "Sleeps through the night", emoji: "😴", value: 3, category: "temperament", effect: null },
  { obsolete: true, text: "Good with kids", emoji: "🧒", value: 2, category: "temperament",
    effect: { type: "burst", layer: "front", params: { color: "#fbbf24", count: 26, spread: 130 } } },
  { text: "Fine with cats", emoji: "🐈", value: 2, category: "temperament", group: "cats", effect: null },
  { text: "Ignores you completely outdoors", emoji: "🙉", value: -2, category: "temperament", group: "training", effect: null },
  { text: "Barks at nothing for forty minutes", emoji: "📢", value: -5, category: "temperament",
    effect: { type: "shake", layer: "front", params: { intensity: 3, period: 900 } } },
  { text: "Banned from the dog park", emoji: "🚫", value: -5, category: "temperament",
    effect: { type: "glitch", layer: "front", params: { color: "#ef4444", intensity: 0.6, scanlines: false } } },
  { text: "Bit a groomer once", emoji: "🩹", value: -5, category: "temperament",
    effect: { type: "chromatic", layer: "subject", params: { offset: 3 } } },
  { text: "Ate a child", emoji: "💀", value: -9, category: "temperament",
    effect: { type: "invert", layer: "subject", params: { amount: 0.8 } } },
  { text: "Kleptomania", emoji: "💍", value: -5, category: "temperament", effect: null },
  { text: "Afraid of men in hats", emoji: "🎩", value: -1, category: "temperament", effect: null },
  { text: "Afraid of the floor", emoji: "🧊", value: -5, category: "temperament",
    effect: { type: "bounce", layer: "subject", params: { period: 1200 } } },
  { text: "Believes he is a person", emoji: "🧍", value: 1, category: "temperament", effect: null },
  { text: "Knows when you're sad", emoji: "🫂", value: 4, category: "temperament",
    effect: { type: "pulse", layer: "back", params: { color: "#f472b6", period: 2400, radius: 180 } } },
  { text: "Respects the UPS driver, hates the mailman", emoji: "📦", value: 0, category: "temperament", effect: null },
  { text: "Big strong barks", emoji: "📣", value: 4, category: "temperament", group: "voice",
    effect: { type: "ripple", layer: "back", params: { color: "#93c5fd", rings: 4, speed: 1.2, maxRadius: 200 } } },
  { text: "Existential crisis", emoji: "🕳️", value: -5, category: "temperament",
    effect: { type: "ghost", layer: "subject", params: { opacity: 0.6, blur: 0.8 } } },
  { text: "Fetch world champion", emoji: "🥇", value: 8, category: "temperament", group: "fetch",
    effect: { type: "burst", layer: "front", params: { color: "#fbbf24", count: 46, spread: 210, confetti: true } } },
  { text: "Fetch regional champion", emoji: "🥈", value: 5, category: "temperament", group: "fetch",
    effect: { type: "burst", layer: "front", params: { color: "#cbd5e1", count: 28, spread: 150 } } },
  { text: "Amateur fetch player", emoji: "🎾", value: 2, category: "temperament", group: "fetch",
    effect: { type: "burst", layer: "front", params: { color: "#bef264", count: 14, spread: 100 } } },
  { text: "Practicing therapist", emoji: "🛋️", value: 5, category: "temperament", group: "job",
    effect: { type: "pulse", layer: "back", params: { color: "#4ade80", period: 2800, radius: 190 } } },
  { text: "Homies with da cats", emoji: "🐈", value: 3, category: "temperament", group: "cats", effect: null },
  { text: "Does math for treats", emoji: "🧮", value: 2, category: "temperament",
    effect: { type: "halo", layer: "subject", params: { color: "#38bdf8", size: 12 } } },
  { text: "Howls in perfect pitch", emoji: "🎻", value: 3, category: "temperament", group: "voice",
    effect: { type: "ripple", layer: "back", params: { color: "#c4b5fd", rings: 4, speed: 1, maxRadius: 170 } } },
  { text: "Predicts earthquakes, badly", emoji: "🔮", value: -1, category: "temperament",
    effect: { type: "shake", layer: "front", params: { intensity: 2, period: 1400 } } },
  { text: "Sees something in the hallway you don't", emoji: "👻", value: -3, category: "temperament",
    effect: { type: "fog", layer: "front", params: { color: "#cbd5e1", bands: 2, opacity: 0.25, speed: 0.4 } } },
  { text: "Leans on people. Heavily.", emoji: "🫠", value: 2, category: "temperament", effect: null },
  { text: "Remembers a house that no longer exists", emoji: "🏘️", value: -1, category: "temperament",
    effect: { type: "tint", layer: "subject", params: { sepia: 0.6, hue: 0, saturate: 0.7 } } },
  { text: "Knows where the lost things are", emoji: "🗝️", value: 3, category: "temperament", effect: null },
  { text: "Forgets you exist between 2 and 3pm", emoji: "🕑", value: -4, category: "temperament",
    effect: { type: "ghost", layer: "subject", params: { opacity: 0.7 } } },
  { text: "Barks in a language older than barking", emoji: "🔣", value: -2, category: "temperament", group: "voice",
    effect: { type: "ripple", layer: "back", params: { color: "#4c1d95", rings: 4, speed: 0.7, maxRadius: 170 } } },
  { text: "Knows things no dog should know", emoji: "📿", value: -1, category: "temperament", group: "mind",
    effect: { type: "halo", layer: "subject", params: { color: "#6d28d9", size: 12 } } },
  { text: "Waits at the station every evening", emoji: "🚉", value: 4, category: "temperament", group: "loyalty", effect: null },
  { text: "Keeps trying to tell you about a well", emoji: "🆘", value: 2, category: "temperament", effect: null },
  { text: "This is fine", emoji: "🫖", value: 0, category: "temperament",
    effect: { type: "rise", layer: "front", params: { color: "#f97316", count: 26, speed: 1.2, sway: 1.5, size: 4, glow: true } } },
  { text: "Laughs at you when you miss", emoji: "😆", value: -2, category: "temperament", effect: null },
  { text: "Won't help unless you pin a medal on him", emoji: "🏅", value: -2, category: "temperament", effect: null },
  { text: "Bit the only hand that fed him", emoji: "✋", value: -3, category: "temperament", effect: null },
  { text: "Quietest when he's closest", emoji: "🔇", value: -2, category: "temperament",
    effect: { type: "vignette", layer: "front", params: { color: "#020617", opacity: 0.55 } } },
  { text: "Says the word woof. Sarcastically.", emoji: "🙄", value: -1, category: "temperament", group: "voice", effect: null },
  { text: "Says I love you, but only on camera", emoji: "📹", value: 1, category: "temperament", group: "voice", effect: null },
  { text: "Smarter than the whole crew. Nobody noticed.", emoji: "🛰️", value: 2, category: "temperament", group: "mind", effect: null },
  { text: "Was told to wait outside the pizza place. Did.", emoji: "🍕", value: 2, category: "temperament", group: "loyalty", effect: null },
  { text: "Waited twenty years on a dung heap. Worth it.", emoji: "⛵", value: 3, category: "temperament", group: "loyalty", effect: null },
  { text: "Can pronounce the letter F. Only the letter F.", emoji: "🔤", value: 1, category: "temperament", effect: null },
  { text: "Cave canem. He is the canem.", emoji: "🏛️", value: 1, category: "temperament", effect: null },
  { text: "Victorian. Refuses to smile.", emoji: "🎩", value: -1, category: "temperament",
    effect: { type: "tint", layer: "subject", params: { sepia: 0.9, hue: 0, saturate: 0.6 } } },
  { text: "Barks in binary", emoji: "📡", value: -1, category: "temperament", group: "voice", effect: null },

  // ----- civic life: the shopping cart test, both ways. Not exclusive: plenty of dogs do both. -----
  { text: "Returns other people's shopping carts", emoji: "🛒", value: 3, category: "temperament", effect: null },
  { text: "Picks up after himself", emoji: "🧹", value: 3, category: "temperament", effect: null },
  { text: "Holds the door. Waits a bit too long.", emoji: "🚪", value: 2, category: "temperament", effect: null },
  { text: "Lets you merge", emoji: "🚗", value: 2, category: "temperament", effect: null },
  { text: "Brings the neighbors' trash cans in", emoji: "🗑️", value: 2, category: "temperament", effect: null },
  { text: "Always brings a dish to the potluck", emoji: "🥘", value: 2, category: "temperament", effect: null },
  { text: "Waves at every bus driver", emoji: "👋", value: 1, category: "temperament", effect: null },
  { text: "Tips twenty percent", emoji: "💵", value: 2, category: "temperament",
    effect: { type: "burst", layer: "front", params: { color: "#4ade80", count: 18, spread: 120 } } },
  { text: "Returns library books early", emoji: "📚", value: 2, category: "temperament", effect: null },
  { text: "Donates blood. Dog blood.", emoji: "🩸", value: 3, category: "temperament",
    effect: { type: "halo", layer: "subject", params: { color: "#f87171", size: 10 } } },
  { text: "Takes two parking spaces", emoji: "🅿️", value: -3, category: "temperament", effect: null },
  { text: "Reclines all the way on flights", emoji: "💺", value: -3, category: "temperament", effect: null },
  { text: "Leaves one second on the microwave", emoji: "⏲️", value: -2, category: "temperament", effect: null },
  { text: "Takes calls on speaker in public", emoji: "📱", value: -3, category: "temperament",
    effect: { type: "ripple", layer: "back", params: { color: "#fde68a", rings: 3, speed: 1.2, maxRadius: 150 } } },
  { text: "Replies all", emoji: "📧", value: -2, category: "temperament", effect: null },
  { text: "Doesn't pick up his own poop", emoji: "💩", value: -4, category: "temperament", effect: null },
  { text: "Stands on the left of the escalator", emoji: "🧍", value: -2, category: "temperament", effect: null },
  { text: "Merges at the last second", emoji: "🚦", value: -3, category: "temperament", effect: null },
  { text: "Cuts the line at the water bowl", emoji: "🚰", value: -3, category: "temperament", effect: null },
  { text: "Never tips", emoji: "🧾", value: -3, category: "temperament", effect: null },
  { text: "Unionized the other dogs", emoji: "✊", value: 2, category: "temperament", effect: null },
  { text: "Quiet-quit being a good boy", emoji: "🪫", value: -2, category: "temperament", effect: null },
  { text: "Unspoken rizz", emoji: "😏", value: 2, category: "temperament", effect: null },
  { text: "Knows the Wi-Fi password. Won't share.", emoji: "📶", value: -1, category: "temperament", effect: null },
  // The writers' room, round one: five angles, three reviewers, fifty keepers.
  { text: "Tilts his head. Charges dropped.", emoji: "🥺", value: 3, category: "temperament", effect: null },
  { text: "Would prefer not to", emoji: "🗂️", value: -2, category: "temperament", effect: null },
  { text: "Took the fall for the cat", emoji: "🐈", value: 3, category: "temperament", effect: null },
  { text: "Never talks about Belgium", emoji: "🤐", value: -1, category: "temperament", effect: null },
  { text: "Wants to talk about an opportunity", emoji: "💼", value: -3, category: "temperament", effect: null },
  { text: "Spells walk. You've moved to French.", emoji: "📝", value: 1, category: "temperament", effect: null },
  { text: "Reported your fence to the HOA", emoji: "📏", value: -3, category: "temperament", effect: null },
  { text: "Mods a Discord server. Power-mad.", emoji: "🛡️", value: -2, category: "temperament", effect: null },
  { text: "Not the same since the magician", emoji: "🎩", value: -2, category: "temperament", effect: null },
  { text: "Took the credit for Togo's run", emoji: "🛷", value: -2, category: "temperament", effect: null },
  { text: "Forgave you for something you forgot", emoji: "🕊️", value: 2, category: "temperament", effect: null },
  { text: "Told a king to stand out of his sun", emoji: "🛢️", value: 1, category: "temperament", effect: null },
  { text: "Throws a homecoming after the bins", emoji: "🎉", value: 3, category: "temperament", effect: null },
  // The boring writers' room: extremely mundane, some suspiciously so.
  { text: "Seemed like a nice dog", emoji: "🗣️", value: 0, category: "temperament", effect: null },
  { text: "Neither agrees nor disagrees", emoji: "☑️", value: -1, category: "temperament", effect: null },
  { text: "The neighbor waves. He nods.", emoji: "👋", value: 1, category: "temperament", effect: null },
  // The trait tournament, round 1: picked by a human from ten writers' best.
  { text: "Forgives easily. Remembers everything.", emoji: "🐘", value: 3, category: "temperament", effect: null },
];
